jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            http_basic:
                realm: "Secured Area"
    access_control:
        - { path: ^/car, roles: ROLE_USER }
    providers:
        in_memory:
            memory:
                users:
                    danny: { password: lolcats, roles: 'ROLE_USER' }
                    dan: { password: lolkitties, roles: 'ROLE_ADMIN' }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
