parameters:
#    dan_finnie_gas.example.class: DanFinnie\GasBundle\Example

services:
#    dan_finnie_gas.example:
#        class: %dan_finnie_gas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
